### ISSUE TITLE
nil pointer dereference in federatedseed controller

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3621]
**How to categorize this issue?**

/kind bug

**What happened**:

```
$ k -n garden logs gardenlet-68976689d5-pn462

E0224 07:56:30.062058       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 6155 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f39e80, 0x33ac580)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1f39e80, 0x33ac580)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions.getShootStateExtensionStateAndResources(0x0, 0x2201476, 0xb, 0xc02e5e9450, 0x0, 0xc003048ac0, 0x3e, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go:178 +0x26
github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions.(*ShootStateControl).CreateShootStateSyncReconcileFunc.func1(0x24e0ec0, 0xc02e6b27c0, 0x0, 0x0, 0xc003048ac0, 0x3e, 0x0, 0x0, 0xc02dcece30, 0x0)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go:91 +0x350
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc02ff60270, 0x24e0ec0, 0xc02e6b27c0, 0x0, 0x0, 0xc003048ac0, 0x3e, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:102 +0x6f
github.com/gardener/gardener/pkg/controllerutils.worker.func1(0x24fe260, 0xc02e998880, 0x2487820, 0xc02ff60270, 0x24e0ec0, 0xc02e6b27c0, 0xc02ff5a220, 0x16, 0x439400)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:114 +0x13e
github.com/gardener/gardener/pkg/controllerutils.worker(0x24e0ec0, 0xc02e6b27c0, 0x24fe260, 0xc02e998880, 0xc02ff5a220, 0x16, 0x2487820, 0xc02ff60270)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:131 +0x7a
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2.1(0x24e0ec0, 0xc02e6b27c0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:72 +0x6b
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001c9c6e8)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00a8e9ee8, 0x2485200, 0xc02e5f94d0, 0xc02e6b2701, 0xc02e53d0e0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c9c6e8, 0x3b9aca00, 0x0, 0xc01bf25b01, 0xc02e53d0e0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x24e0ec0, 0xc02e6b27c0, 0xc001c9c748, 0x3b9aca00, 0x0, 0x1)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2(0x24e0ec0, 0xc02e6b27c0, 0x24fe260, 0xc02e998880, 0xc02ff5a220, 0x16, 0x2487820, 0xc02ff60270, 0xc02e772fc0, 0xc02e72d508)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:71 +0xd2
created by github.com/gardener/gardener/pkg/controllerutils.CreateWorker
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:70 +0x285
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x1cc7de6]

goroutine 6155 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1f39e80, 0x33ac580)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions.getShootStateExtensionStateAndResources(0x0, 0x2201476, 0xb, 0xc02e5e9450, 0x0, 0xc003048ac0, 0x3e, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go:178 +0x26
github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions.(*ShootStateControl).CreateShootStateSyncReconcileFunc.func1(0x24e0ec0, 0xc02e6b27c0, 0x0, 0x0, 0xc003048ac0, 0x3e, 0x0, 0x0, 0xc02dcece30, 0x0)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/federatedseed/extensions/shootstate_control.go:91 +0x350
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc02ff60270, 0x24e0ec0, 0xc02e6b27c0, 0x0, 0x0, 0xc003048ac0, 0x3e, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:102 +0x6f
github.com/gardener/gardener/pkg/controllerutils.worker.func1(0x24fe260, 0xc02e998880, 0x2487820, 0xc02ff60270, 0x24e0ec0, 0xc02e6b27c0, 0xc02ff5a220, 0x16, 0x439400)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:114 +0x13e
github.com/gardener/gardener/pkg/controllerutils.worker(0x24e0ec0, 0xc02e6b27c0, 0x24fe260, 0xc02e998880, 0xc02ff5a220, 0x16, 0x2487820, 0xc02ff60270)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:131 +0x7a
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2.1(0x24e0ec0, 0xc02e6b27c0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:72 +0x6b
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001c9c6e8)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00a8e9ee8, 0x2485200, 0xc02e5f94d0, 0xc02e6b2701, 0xc02e53d0e0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c9c6e8, 0x3b9aca00, 0x0, 0xc01bf25b01, 0xc02e53d0e0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x24e0ec0, 0xc02e6b27c0, 0xc001c9c748, 0x3b9aca00, 0x0, 0x1)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2(0x24e0ec0, 0xc02e6b27c0, 0x24fe260, 0xc02e998880, 0xc02ff5a220, 0x16, 0x2487820, 0xc02ff60270, 0xc02e772fc0, 0xc02e72d508)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:71 +0xd2
created by github.com/gardener/gardener/pkg/controllerutils.CreateWorker
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:70 +0x285
```

It seems to happen after https://github.com/gardener/gardener/pull/3550

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by stoyanr** [comment]
Deleting all backupentries for shoots that have been already deleted from the seed workarounds the issue at least temporarily. We should probably look into why these backupentries still exist in the first place - this is probably also an issue since only some of them remain, and only in some cases.

**Comment by plkokanov** [comment]
I talked with @kris94 to also include checks in the migration integration test for orphaned resources and to see if those backupentries getting orphaned is buggy behaviour or not.

Currently the migrate method for the backupentries doesn't do anything:
```
// Migrate migrates the BackupEntry.
func (a *actuator) Migrate(_ context.Context, _ *extensionsv1alpha1.BackupEntry) error {
	return nil
}
```
So this might be causing it.
