### ISSUE TITLE
gardenlet: concurrent map writes

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4443]
/area quality
/kind bug
/priority 3

**What happened**:

```
fatal error: concurrent map writes

goroutine 66549 [running]:
runtime.throw(0x254a142, 0x15)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc004a03be0 sp=0xc004a03bb0 pc=0x436fb2
runtime.mapassign_faststr(0x2207420, 0xc018c5f260, 0x253d13d, 0xd, 0xc01bc12e80)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc004a03c48 sp=0xc004a03be0 pc=0x414671
github.com/gardener/gardener/pkg/operation/botanist.(*Botanist).DeployCloudProviderSecret(0xc01933e930, 0x2854a98, 0xc00005a030, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/pkg/operation/botanist/secrets.go:207 +0x2a7 fp=0xc004a03d18 sp=0xc004a03c48 pc=0x1f6b2a7
github.com/gardener/gardener/pkg/operation/botanist.(*Botanist).DeployCloudProviderSecret-fm(0x2854a98, 0xc00005a030, 0x256b0de, 0x27)
	/go/src/github.com/gardener/gardener/pkg/operation/botanist/secrets.go:181 +0x47 fp=0xc004a03d50 sp=0xc004a03d18 pc=0x1fc26e7
github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode.func1(0xc01af6fb20, 0x256b0de, 0x27, 0x2854a98, 0xc00005a030)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:223 +0x1cf fp=0xc004a03fb8 sp=0xc004a03d50 pc=0x1cef2af
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc004a03fc0 sp=0xc004a03fb8 pc=0x46d361
created by github.com/gardener/gardener/pkg/utils/flow.(*execution).runNode
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:218 +0x14f
```

Checkout full logs in [gardenlet-dd84747cc-wd5kj.log](https://github.com/gardener/gardener/files/6884659/gardenlet-dd84747cc-wd5kj.log)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.28.0-dev-489e985691671faac0a73bc9a4a4cf62c2acbcc2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timuthy** [comment]
Root cause: [storeStaticTokenAsSecrets](https://github.com/gardener/gardener/blob/584ae9587896f5c04cd33a13e14b1774b37d32d9/pkg/operation/botanist/secrets.go#L338) writes to `b.CheckSums` without acquiring the lock from `Operation`.
